app:
    resource: '@AppBundle/Controller/'
    type: annotation



club:
    resource: "@ClubBundle/Controller/"
    type:     annotation
    prefix:   /

rh:
    resource: "@RHBundle/Controller/"
    type:     annotation
    prefix:   /


eleve:
    resource: "@EleveBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


